from threading import *
import time
def display():
    print('Current Thread:',current_thread().name,'Started...')
    time.sleep(3)
    print('Currendt Thread:',current_thread().name,'Ended...')
t1=Thread(target=display,name='Child Thread 1')
t2=Thread(target=display,name='Child Thread 2')
t3=Thread(target=display,name='Child Thread 3')
t4=Thread(target=display,name='Child Thread 4')
t1.start()
t2.start()
t3.start()
t4.start()
print(t1.name,'Is Alive:',t1.is_alive( ))
print(t2.name,'Is Alive:',t2.is_alive( ))
print(t2.name,'Is Alive:',t3.is_alive( ))
print(t4.name,'Is Alive:',t4.is_alive( ))
print('The number of active threads:',active_count())
time.sleep(10)
print(t1.name,'Is Alive:',t1.is_alive( ))
print(t2.name,'Is Alive:',t2.is_alive( ))
print(t2.name,'Is Alive:',t3.is_alive( ))
print(t4.name,'Is Alive:',t4.is_alive( ))
print('The number of active threads:',active_count())
