import logging
logger=logging.getLogger('custom_logger')
logger.setLevel(logging.DEBUG)
consoleHandler= logging.StreamHandler()
fileHandler=logging.FileHandler('cust_logger.log',mode='w')
consoleHandler.setLevel(logging.ERROR)
fileHandler.setLevel(logging.INFO)
formatter1=logging.Formatter('%(asctime)s:%(levelname)s:%(name)s:%(message)s',
                            datefmt='%d/%m/%Y %H:%M:%S'
                            )
formatter2=logging.Formatter('%(levelname)s:%(message)s')       
fileHandler.setFormatter(formatter1)
consoleHandler.setFormatter(formatter2)
logger.addHandler(fileHandler)
logger.addHandler(consoleHandler)
logger.critical('critical message')
logger.error('error message')
logger.warning('warning message')
logger.info('info message')
logger.debug('debug message')
