import os
# os.makedirs('Valmiki/varun/sandesh')
# os.makedirs('Videos/pythonVideos/filehandling')
# os.rmdir('Videos/pythonVideos')
# os.removedirs('Videos/pythonVideos/filehandling')
# os.rename('Videos/pythonVideos','Videos/Python Videos')
# os.makedirs('cwd/material/java/selenium') 
# os.rmdir('cwd/material/java/java1.txt')
# os.makedirs('cwd/material/java/selenium')
# os.rename('cwd/material/testing/selenium/java3.txt','cwd/material/testing/selenium/testing3.txt')
# l=os.listdir('cwd/material')
l=os.walk('cwd')
# print(type(l))
# for g in l:
#     print(g)
for path,name,file1 in l:
    print('Dir path:',path)
    print('Dir name:',name)
    print('Dir file:',file1)
    print()
